### ISSUE TITLE
Binding generator does not respect "is_nullable" on TensorList typed arguments

### ISSUE THREAD

**Issue by jerry73204** [LaurentMazare/tch-rs#322]
When trying to select indexes on multiple dimensions, it stumbled me that I'm not able to skip some dimensions when calling [`Tensor::index(indices: &[T])`](https://docs.rs/tch/0.3.1/tch/struct.Tensor.html#method.index). The C++ ATen on the other hand can accept optional tensors ([code](https://github.com/pytorch/pytorch/blob/a291b254ee486c803ecbe0ca6a390a3ff124b11a/aten/src/ATen/native/TensorAdvancedIndexing.cpp#L285)). I looked at the `Declarations-v1.7.0.yaml`. The corresponding argument has `is_nullable = true` with type `TensorList`. However, our binding generator does not respect it.

```
- name: index
  ...
  schema_string: aten::index.Tensor(Tensor self, Tensor?[] indices) -> Tensor
  ...
  arguments:
  - annotation: null
    dynamic_type: Tensor
    is_nullable: false
    name: self
    type: const Tensor &
  - annotation: null
    dynamic_type: TensorList
    is_nullable: true
    name: indices
    type: TensorList
```

IMO, the corresponding Rust signature should be one of the candidates:
- `fn index<T: Borrow<Tensor>>(indices: &[Option<T>])`
- `fn index(indices: impl OptionalTensorList)` where `OptionalTensorList` is a trait that accepts `&[Option<T>]`, `&[&Option<T>]` and `&[T]`.

I'm considering merging this change to the new Rust binding generator (#318). Also, I acknowledge that my multi-dimensional indexing was not correct in #60 that it should use `index()` instead of `index_select()`. @LaurentMazare are you comfortable with this plan?
