### ISSUE TITLE
error while loading shared libraries: libtorch_cuda.so not found

### ISSUE THREAD

**Issue by EricLBuehler** [LaurentMazare/tch-rs#824]
Hello everybody,

I am using `tch-rs` as an FFI between Rust (Candle) and C++ (Pytorch). However, during my testing, I get the following error:
`target/debug/tch_test: error while loading shared libraries: libtorch_cuda.so: cannot open shared object file: No such file or directory`

Here is the program:
```rust
use tch::Tensor;

fn main() {
    let t = Tensor::from_slice(&[1.1f32, 2.1, 3.1]);
    t.print();
}
```
And my Cargo.toml:
```toml
[package]
name = "tch_test"
version = "0.1.0"
edition = "2021"

[dependencies]
tch = "0.14.0"
```
I do not have a `build.rs` file, and this is run on a clean instance. I would appreciate any help!
