### ISSUE TITLE
Build fails unless I downgrade `google-glog` to 0.6.0.

### ISSUE THREAD

**Issue by iago-lito** [LaurentMazare/tch-rs#851]
With this simple project:

- `Cargo.toml`
```toml
[package]
name = "tch_test"
version = "0.1.0"
edition = "2021"

[dependencies]
tch = { version = "0.15.0", features = ["download-libtorch"] } 
```

- `src/main.rs`
```rust
fn main() {}
```

After a clean `rustup update` and `sudo pacman -Syu` on archlinux, I get the following build failure:
```sh
$ cargo check
```

[`cargo_check.log`](https://github.com/LaurentMazare/tch-rs/files/14434876/cargo_check.log)

The build suceeds if I downgrade my [google-glog](https://archlinux.org/packages/extra/x86_64/google-glog/) package from `0.7.0` to `0.6.0`.

I can read nothing [on the README page](https://github.com/LaurentMazare/tch-rs) that refers to this library. Maybe it should be specified that it is actually used/useful? And that a specific version of it should be available on the system?
